yokuba/King-Kong-Survey

app/controllers/index.rb

@yokuba @jeder28 @utahrim 
JOB DONE CALLING IT A DAY

add index page to redirect

---

app/controllers/surveys.rb

Routes for surveys yay!! :hamburger: :hamster:

Heather controller

---

config/environment.rb
db/seeds.rb

add seeds for user, survey, question and choices

---

app/controllers/users.rb

Added user routes. could be subject to change later :question:

User route

---

app/controllers/questions.rb

Heather controler questions

---

app/controllers/users.rb

@yokuba @utahrim @jeder28 
there was a route that needed fixing :disappointed:

fixed route

---

app/views/survey/index.erb

Add list of surveys

---

app/views/survey/show.erb

@utahrim @yokuba @jeder28 
there were two surveys folders. I deleted the singular one.

remove old survey folder

---

app/controllers/questions.rb
app/views/questions/new.erb

added a new erb and refactor the route a bit to be able to associate a question to a user, eventually.

Question create

---

Gemfile.lock
app/helpers/auth.rb
app/views/layout.erb
app/views/surveys/index.erb
app/views/users/login.erb
app/views/users/new.erb

@utahrim @yokuba @jeder28 
User sign in and login will give a session, as well as clearing the session when logging out.

User login create

---

app/views/layout.erb

there was a merge conflict; fixed it

fix header conflict

---

app/controllers/questions.rb
app/controllers/surveys.rb
app/models/question.rb
app/views/questions/show.erb
app/views/surveys/index.erb
app/views/surveys/show.erb

@utahrim @yokuba @jeder28 
YOU WANT LINKS? TAKE THEM

Survey logic

---

app/models/user.rb

@utahrim @yokuba @jeder28 
there was an extra comma that broke everything in the user model. I took it out.

remove typo

---

app/controllers/questions.rb
app/controllers/surveys.rb
app/views/surveys/show.erb

@jeder28 @yokuba @utahrim
fixed survey start bug. the @question variable was breaking everything as well as the route

Survey bug

---

app/controllers/users.rb
app/models/response.rb
app/views/users/show.erb

logic should go in the model, but this works for now

fixed user profile page to display surveys taken- needs to be DRYed!

---

Gemfile
Gemfile.lock
app/controllers/auth.rb
app/controllers/questions.rb
app/controllers/responses.rb
app/controllers/surveys.rb
app/views/layout.erb
app/views/responses/show.erb
config/environment.rb
public/css/application.css

I added some sinatra flashes on redirects. It'll display below the header but above the content. My biggest problem was styling it. I feel like we should use the flash[:error] on the else statements in the controllers instead of @errors...?
Ignore the responses/show erb and controller. I forgot to put that in another branch. :(

Flash msgs

---

app/controllers/questions.rb
app/controllers/surveys.rb
app/controllers/users.rb

@jeder28 @utahrim @yokuba 
I've used the helper method current_user to flash the user that they must be logged in first to play or create a survey. So that basically makes the site users only, no anonymous people.

Login auth

---

public/css/application.css
public/js/application.js

@jeder28 @yokuba @utahrim 
I added some jquery to make the flashes fadeIn on load, and fadeOut after 2 seconds.

Jquery flash

---

app/controllers/questions.rb
app/controllers/surveys.rb
app/views/layout.erb
app/views/questions/_new_question.erb
app/views/questions/_new_question_finish.erb
app/views/questions/new.erb
app/views/surveys/new.erb
public/js/application.js

So I was trying to have a more elegant ajax solution for this:
1.  Have a button that saves and gives you a new question form to enter another question.
2. Have a second button that saves the question and completes by taking you to the home page
Right now I put the complete button above the form so when you are done writing questions you click complete and takes you to the index page, it will not save any content in the question form when you click complete. The only way to save a question is the complete question button below the question form at this time.

Heather ajax new questions

---

app/controllers/questions.rb
app/controllers/surveys.rb
app/controllers/users.rb
app/models/question.rb
app/models/response.rb
app/views/users/show.erb

Sorry about the earlier merge conflict. This one should be okay.

Fix bad demeter user

---

app/controllers/users.rb
app/views/layout.erb
app/views/questions/_new_question.erb
app/views/questions/_new_question_finish.erb
app/views/questions/show.erb
app/views/responses/show.erb
app/views/surveys/_create_survey.erb
app/views/surveys/index.erb
app/views/surveys/new.erb
app/views/surveys/show.erb
app/views/users/login.erb
app/views/users/new.erb
app/views/users/show.erb
public/css/application.css

Some bugs were fixed in this process too like removing a line that was requiring pry and a couple of other things I ran into.

Heather css

---

app/controllers/auth.rb
app/controllers/questions.rb
app/views/users/_user_login_form.erb
app/views/users/_user_signup_form.erb
app/views/users/login.erb
app/views/users/new.erb
public/css/application.css
public/js/application.js

I added a link below register and login. Under register, it'll ask if the user has an account already. if they do, they can click "Log in now!" and it'll show an ajaxed login page right on the same page. vice versa or the login page if the user doesn't have an account.

Login condense ajax
